---
abstract: 'Common text filter API'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Pipe
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Complex: 0
  Class::Accessor::Constructor: 0
  List::Util: 0
  Sub::Name: 0
  UNIVERSAL::require: 0
  perl: 5.6.0
resources:
  bugtracker: http://search.cpan.org/dist/Text-Pipe/
  homepage: http://search.cpan.org/dist/Text-Pipe/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/text-pipe.git
version: 0.09
