--- 
abstract: ~
author: 
  - Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>
build_requires: 
  Test::Compile: 0
  Test::More: 0
  UNIVERSAL::require: 0
  YAML: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-Pipe
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor::Complex: 0
  Class::Accessor::Constructor: 0
  List::Util: 0
  Sub::Name: 0
  UNIVERSAL::require: 0
  perl: 5.6.0
version: 0.03
