---
abstract: 'Common text filter API'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  Test::More: 0.70
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Pipe
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Complex: 0
  Class::Accessor::Constructor: 0
  List::Util: 0
  Sub::Name: 0
  UNIVERSAL::require: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
